### ISSUE TITLE
How to run script in windows?

### ISSUE THREAD

**Issue by levlandau** [manticorp/GCodeArcOptimiser#1]
I installed Windows PHP but don't have a web server running on my Windows 7 PC.

I made the cli.php file as the instructions stated, but when I run the file using the command in the instructions I get the error below. What am I doing wrong? The command is being called from the same directory as the other files for this program.

```
C:\gcodearcoptimiser>php cli.php -f "SomeGcodeFile.g" -o "MyProcessedFile.g"
PHP Fatal error:  Uncaught Error: Call to undefined function processGcode() in C:\gcodearcoptimiser\cli.php:9
Stack trace:
#0 {main}
  thrown in C:\gcodearcoptimiser\cli.php on line 9

Fatal error: Uncaught Error: Call to undefined function processGcode() in C:\gcodearcoptimiser\cli.php:9
Stack trace:
#0 {main}
  thrown in C:\gcodearcoptimiser\cli.php on line 9

```

**Comment by manticorp** [comment]
Ah yeah sorry, try putting:

```
include "functions.php";
```

At the top of the file.
